version: "3"
services:

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "${TRANSMISSION_EXTERNAL_PORT}:9091"
      - "${TRANSMISSION_PEER_PORT}:${TRANSMISSION_PEER_PORT}"
      - "${TRANSMISSION_PEER_PORT}:${TRANSMISSION_PEER_PORT}/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - "${TRANSMISSION_CONFIG_PATH}:/config"
      - "${TRANSMISSION_DOWNLOADS_PATH}:/complete"
      - "${TRANSMISSION_WATCH_PATH}:/watch"

  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - "${SONARR_EXTERNAL_PORT}:8989"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - "${SONARR_CONFIG_PATH}:/config"
      - "${TV_PATH}:/tv"
      - "${TRANSMISSION_DOWNLOADS_PATH}:/complete"

  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - "${RADARR_EXTERNAL_PORT}:7878"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - "${RADARR_CONFIG_PATH}:/config"
      - "${MOVIES_PATH}:/movies"
      - "${TRANSMISSION_DOWNLOADS_PATH}:/complete"

  jackett:
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "${JACKETT_EXTERNAL_PORT}:9117"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - "${JACKETT_CONFIG_PATH}:/config"
      - "${JACKETT_BLACKHOLE_PATH}:/downloads"

  lidarr:
    image: linuxserver/lidarr
    restart: unless-stopped
    ports:
      - "${LIDARR_EXTERNAL_PORT}:8686"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - "${LIDARR_CONFIG_PATH}:/config"
      - "${MUSIC_PATH}:/music"
      - "${TRANSMISSION_DOWNLOADS_PATH}:/complete"

  plex:
    image: linuxserver/plex
    restart: unless-stopped
    network_mode: "host"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      VERSION: latest
      TZ: ${TIMEZONE}
    volumes:
      - "${PLEX_CONFIG_PATH}:/config"
      - "${PLEX_TRANSCODING_PATH}:/transcode"
      - "${MOVIES_PATH}:/data/movies"
      - "${TV_PATH}:/data/tv"
      - "${MUSIC_PATH}:/data/music"

  homeassistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - "${HASS_CONFIG_PATH}:/config"

  duckdns:
    image: linuxserver/duckdns
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAIN}
      TOKEN: ${DUCKDNS_TOKEN}
    volumes:
      - "${DUCKDNS_CONFIG_PATH}:/config"
